services:
  # 1. Spring Boot 서버
  api-server:
    image: carune99/ticket-server:latest
    container_name: ticket-server
    build: .  # 현재 폴더의 Dockerfile로 빌드
    env_file:
      - .env
    ports:
      - "8080:8080" # 외부 접속용 포트
    environment:

      LOGGING_FILE_NAME: /logs/ticket-server.log
      TZ: Asia/Seoul
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "prometheus,health"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
      # MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/ticket_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      # Redis
      SPRING_DATA_REDIS_HOST: redis-container
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - mysql-container
      - redis-container
    volumes:
      - ./logs:/logs  # 호스트의 logs 폴더와 컨테이너의 /logs 연결
    restart: always

  # 2. MySQL
  mysql-container:
    image: mysql:8.0
    container_name: ticket-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # 3. Redis
  redis-container:
    image: redis:latest
    container_name: ticket-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD} # AOF 설정 (데이터 증발 방지)
    volumes:
      - ./redis-data:/data

  # 4. Prometheus (데이터 수집)
  prometheus:
    image: prom/prometheus:latest
    container_name: ticket-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api-server
    networks:
      - default

  # 5. Grafana (데이터 시각화)
  grafana:
    image: grafana/grafana:latest
    container_name: ticket-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - prometheus
    networks:
      - default