scrape_configs:
  #- job_name: 'spring-boot-app'
  - job_name: 'spring-boot-local'
    metrics_path: '/actuator/prometheus' # 스프링 부트가 정보 주는 주소
    scrape_interval: 2s
    static_configs:
      # docker-compose.yml에 적은 서비스 이름
      #- targets: ['api-server:8080']
      - targets: ['host.docker.internal:8080']