name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 코드 가져오기
      - name: Checkout Code
        uses: actions/checkout@v4

      # 자바 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 권한 부여 및 빌드 (테스트 제외)
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      # Docker 이미지 빌드 및 푸시
      - name: Docker Build & Push
        run: |
          # 도커 허브 로그인
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
          # 이미지 빌드 (DockerHub아이디/프로젝트명)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ticket-server .
          
          # 도커 허브로 푸시
          docker push ${{ secrets.DOCKER_USERNAME }}/ticket-server

      # AWS EC2 접속 및 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 프로젝트 폴더로 이동
            cd ~/Ticket-Service-Practice
            
            mkdir -p logs
            chmod 777 logs
            
            # 최신 설정 파일 가져오기
            git fetch --all
            git reset --hard origin/main
            git pull origin main
            
            # 실행 중인 컨테
            sudo docker compose down
            
            # 최신 이미지 받아오기
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/ticket-server
            
            # .env 파일 생성 (GitHub Secret 내용을 서버 파일로 만들기)
            # (기존 파일이 있으면 덮어쓰기)
            echo "${{ secrets.ENV_FILE }}" > .env
            
            # Docker Compose 재실행
            sudo docker compose up -d
            
            # 미사용 이미지 삭제 (용량 확보)
            sudo docker image prune -f